#!/usr/bin/env python3
"""Generate sample health data CSV for testing."""

import csv
import random
from datetime import datetime, timedelta

# Sample meals with variety
MEALS = [
    "breakfast burrito with eggs, beans, cheese, and salsa",
    "pizza with pepperoni and extra cheese",
    "grilled chicken salad with mixed greens",
    "pasta carbonara with bacon and parmesan",
    "sushi rolls with salmon and avocado",
    "tacos with beef, cheese, lettuce, and sour cream",
    "stir fry with tofu, broccoli, and rice",
    "burger and fries",
    "greek yogurt with granola and berries",
    "peanut butter and jelly sandwich",
    "pad thai with shrimp",
    "caesar salad with grilled chicken",
    "bean and cheese quesadilla",
    "spicy ramen with soft boiled egg",
    "turkey sandwich on wheat bread",
    "veggie wrap with hummus",
    "fried rice with vegetables",
    "mac and cheese",
    "oatmeal with nuts and banana",
    "soup and salad",
    "chicken wings with ranch",
    "fish tacos with cabbage slaw",
    "beef stew with potatoes and carrots",
    "scrambled eggs with toast",
    "pancakes with maple syrup",
    "chicken curry with rice",
    "vegetable lasagna",
    "pulled pork sandwich",
    "shrimp cocktail",
    "avocado toast with poached egg",
]

ALCOHOL_OPTIONS = [None, "beer", "wine", "cocktail", "whiskey", None, None, None, None, None]


def generate_csv(filename: str, num_rows: int = 200) -> None:
    """Generate a CSV file with sample health entries.

    Args:
        filename (str): Output CSV filename.
        num_rows (int): Number of rows to generate. Defaults to 200.
    """
    print(f"Generating {num_rows} sample entries...")

    with open(filename, "w", newline="", encoding="utf-8") as csvfile:
        fieldnames = [
            "id",
            "date",
            "meal",
            "alcohol",
            "stress",
            "sleep_hours",
            "pain_level",
            "notes",
            "created_at",
        ]
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()

        for i in range(num_rows):
            days_ago = i
            date = (datetime.now() - timedelta(days=days_ago)).strftime("%Y-%m-%d")
            meal = random.choice(MEALS)
            alcohol = random.choice(ALCOHOL_OPTIONS)
            stress = random.randint(1, 10)
            sleep_hours = round(random.uniform(4.5, 9.5), 1)
            pain_level = random.randint(0, 10)
            created_at = datetime.now() - timedelta(days=days_ago, hours=random.randint(0, 23))

            writer.writerow(
                {
                    "id": "",  # Will be generated by importer
                    "date": date,
                    "meal": meal,
                    "alcohol": alcohol if alcohol else "",
                    "stress": stress,
                    "sleep_hours": sleep_hours,
                    "pain_level": pain_level,
                    "notes": f"Sample entry for {meal}",
                    "created_at": created_at.strftime("%Y-%m-%d %H:%M:%S"),
                }
            )

    print(f"✓ Created {filename} with {num_rows} entries")


if __name__ == "__main__":
    output_file = "sample_health_data.csv"
    generate_csv(output_file, num_rows=1000)
    print("\nNext step: Import with:")
    print(
        f"  uv run python scripts/import_csv_to_sqlite.py --csv {output_file} --db data/health.dev.db"
    )
