name: Infra Provisioning
on:
  workflow_dispatch:
    # inputs:
    #   path_to_dockerfile:
    #     description: Path to the dockerfile (default = 'Dockerfile')
    #     default: "Dockerfile"
    #     type: string
    #   docker_build_dir:
    #     description: Docker build directory (default = '.')
    #     default: "."
    #     type: string
    #   image_tag:
    #     description: Tag to apply to images.
    #     type: string
    #     default: snapshot-artifact-yoyomeng2
    #   lifecycle_policy_file:
    #     description: Path to the lifecycle policy JSON file (default = 'configs/infra/policy.json')
    #     default: "configs/infra/policy.json"
    #     type: string
    #   backend_s3_bucket:
    #     description: Name of the S3bucket for Terraform backend
    #     default: "terraform-backend-primary-region-yoyomeng2"
    #     type: string
    #   backend_iam_role:
    #     description: Name of the Terraform backend assumable IAM Role
    #     default: "workload-assumable-role-yoyomeng2"
    #     type: string
    #   github_iam_role:
    #     description: Name of the IAM Role for adding access to ECR repo
    #     default: "github-actions-role-yoyomeng2"
    #     type: string
    #   backend_dynamodb_table:
    #     description: DynamoDB table for State lock
    #     default: "terraform-backend-db-yoyomeng2"
    #     type: string

# concurrency required to avoid terraform lock contention during ECR provisioning
concurrency: ci-${{ github.repository }}-docker-pipeline

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      ECR_REPOSITORY: "${{ github.event.repository.name }}"

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws_account_id }}:role/github-actions-role
          aws-region: ${{ secrets.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: TF init
        shell: bash
        run: |
          set -euxo pipefail \
          cd infra \
          terraform init \
            -backend-config='region=${{ secrets.aws_region }}'
        working-directory: ${{ github.action_path }}

      - name: Create ECR repo [TF apply]
        shell: bash
        run: |
          set -euxo pipefail \
          cd infra \
          terraform apply \
            -var 'aws_account_id=${{ secrets.aws_account_id }}' \
            -auto-approve
        working-directory: ${{ github.action_path }}

    #   - name: Login to Amazon ECR
    #     id: login-ecr
    #     uses: aws-actions/amazon-ecr-login@v2
    #     with:
    #       registries: ${{ secrets.aws_account_id }}

    #   - name: Build, tag, and push image to Amazon ECR
    #     id: build-publish
    #     shell: bash
    #     env:
    #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #       ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
    #       IMAGE_TAG: ${{ inputs.image_tag }}
    #     run: |
    #       docker build "${{ inputs.docker_build_dir }}" -f "${{ inputs.path_to_dockerfile }}" -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
    #       docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
    #       echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
    #       echo "image_tag=$IMAGE_TAG"
    #       echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
